### ISSUE TITLE
privilege target referenced in role configuration  is not defined after upgrade from v3.3 to v4.3

### ISSUE THREAD

**Issue by BlitzInternet** [neos/flow-development-collection#1172]
### Description

After upgrading our application from flow v3.3 to v4.3, flow:core:compile fails with error code 1395869320.

Debugging shows that our Application Policy.yaml gets overridden by the neos/flow Policy.yaml which has an empty privilegeTargets declaration. Roles are merged correctly, but privilegeTargets are not!

Packages/Framework/Neos.Flow/Classes/Configuration/ConfigurationManager.php L842 uses Arrays::arrayMergeRecursiveOverrule with the default $emptyValuesOverride = true, causing later packages to override former packages if empty.
Changing this line to Arrays::arrayMergeRecursiveOverrule($firstConfigurationArray, $secondConfigurationArray, FALSE, FALSE); would fix the issue.

### Steps to Reproduce

1. Upgrade existing application from v3.3 to v4.3.2 which has privilegeTargets defined
2. follow cli upgrade steps until ./flow database:setcharset

#### Expected behavior

Step executed or skipped

#### Actual behavior

Error code 1395869320 during compile because of policy configuration problem.

### Affected Versions

Flow: v4.3.2
Neos/Utility-Arrays: v4.3.2

**Comment by kitsunet** [comment]
This would mean that your package does not require neos/flow in `composer.json` even though it actually requires it to be loaded. Adjusting that and running `./flow flow:package:rescan` should solve this.

**Comment by BlitzInternet** [comment]
Ah, yes, the package still had typo3/flow instead of neos/flow in the composer.json. The code migration didn't touch that apparently. Can confirm it works now for me.

However I still see this as a minor bug, since other package configurations might cause unexpected/undocumented behavior.

**Comment by kitsunet** [comment]
We _could_ maybe do that for policies, but for many configurations it makes a lot of sense to be able to override something to empty.

**Comment by bwaidelich** [comment]
We could remove this line: https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Configuration/Policy.yaml#L19 to reduce these issues.. However this might just fight the symptoms - an invalid package dependency can lead to multiple issues. Maybe we should improve the exception message (https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Security/Policy/PolicyService.php#L123)  to mention the possibility of an invalid loading order.. but is anyone actually reading those? ;)

**Comment by bwaidelich** [comment]
I'll close this for now as the description of the bug doesn't match. But feel free to open up a [discuss thread ](https://discuss.neos.io/) or feature ticket to collect ideas on how to make it easier to prevent unexpected behavior due to invalid package dependencies
